### PR TITLE
More fixes

### PR DESCRIPTION
**Pull request by StephenHodgson**
Overview
---
Updated scene and added demo prefabs.
Fixed some null refs when exiting play mode.

### CODE REVIEW

**Comment by StephenHodgson** [comment]
@johnppella

**Comment by cre8ivepark** [comment]
@StephenHodgson Why did you add demo prefabs? Those should stay in Examples/StandardAssets/Models/ as they are shared in multiple example scenes.
[https://github.com/Microsoft/MixedRealityToolkit-Unity/tree/mrtk_development/Assets/MixedRealityToolkit-Examples/StandardAssets/Models](https://github.com/Microsoft/MixedRealityToolkit-Unity/tree/mrtk_development/Assets/MixedRealityToolkit-Examples/StandardAssets/Models)

**Comment by StephenHodgson** [comment]
Because we were not using prefabs for the demo scene, and we shouldn't have raw mesh asset reference in our scenes.

**Comment by cre8ivepark** [comment]
@StephenHodgson Got it. Could you move them to StandardAssets/Prefabs?

**Comment by StephenHodgson** [comment]
Will do.

**Comment by StephenHodgson** [comment]
Done :)

**Comment by cre8ivepark** [comment]
@StephenHodgson Something seems broken. objects are showing flattened gizmos even though they are not flat. (with default Flatten Auto)
2018-11-09 13_09_08-unity 2018 2 14f1 personal 64bit - boundingboxexample unity - mrtk-public-yoon

**Comment by StephenHodgson** [comment]
Oh, I made them all the same as the plane. I'll revert.

**Comment by StephenHodgson** [comment]
Fixed 
image

**Comment by cre8ivepark** [comment]
@StephenHodgson Oh, I mean, even with the default 'Flatten Auto', the examples used to automatically flatten only thin object (MRTK logo plane object). Now Flatten auto flattens everything.

**Comment by StephenHodgson** [comment]
I'm not sure. This PR doesn't change that code.

**Comment by StephenHodgson** [comment]
Hard to open PRs and test on external branches like this. Maybe we should target John's PR to a feature branch we can pull and test on faster?

**Pull request merged**
